apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    ingressClassName: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: vote-service
            port:
              number: 80
      - path: /result/?(.*)
        pathType: Prefix
        backend:
          service:
            name: result-service
            port:
              number: 80