apiVersion: v1
kind: Pod
metadata:
  name: postgres-app
  labels:
    app: postgres-app
    appType: voting-app
spec:
  containers:
    - name: postgres-app
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data